In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [4]:
cd /Users/hp/Desktop/dataset

C:\Users\hp\Desktop\dataset


In [6]:
data=pd.read_csv('1.02. Multiple linear regression.csv')

In [7]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [9]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [11]:
x=data[['SAT','Rand 1,2,3']]
y=data['GPA']

In [14]:
reg=LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [16]:
reg.intercept_

0.29603261264909486

In [17]:
reg.score(x,y)

0.4066811952814285

In [18]:
x.shape

(84, 2)

In [21]:
r2=reg.score(x,y)
n=x.shape[0]
p=x.shape[1]
adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134023

In [22]:
from sklearn.feature_selection import f_regression

In [23]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [24]:
p_values=f_regression(x,y)[1]

In [26]:
p_values.round(3)

array([0.   , 0.676])

In [ ]:
##summary

In [30]:
reg.summary=pd.DataFrame(data=x.columns.values,columns=['Features'])

In [31]:
reg.summary

Features
0         SAT
1  Rand 1,2,3

In [32]:
reg.summary['Coefficients']=reg.coef_
reg.summary['P_values']=p_values.round(3)

In [33]:
reg.summary

Features  Coefficients  P_values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
scaler=StandardScaler()

In [36]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [39]:
x_scaled=scaler.transform(x)

In [40]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [42]:
reg=LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [43]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [44]:
reg.intercept_

3.330238095238095

In [49]:
reg_summary=pd.DataFrame([['Intercept'],['Rand 1,2,3'],['SAT']],columns=['Features'])
reg_summary['Weights']=reg.intercept_,reg.coef_[1],reg.coef_[0]

In [50]:
reg_summary

Features   Weights
0   Intercept  3.330238
1  Rand 1,2,3 -0.007030
2         SAT  0.171814

In [54]:
reg.predict(x_scaled)

array([3.12193344, 3.0227167 , 3.18145672, 3.05744108, 3.07893924,
       3.0491776 , 3.19634071, 3.20461053, 3.24263988, 3.33027548,
       3.14011817, 3.21452966, 3.15665782, 3.10208671, 3.21122258,
       3.37492322, 3.17318901, 3.04752194, 3.31704714, 3.2244488 ,
       3.18311026, 3.11862213, 3.02106316, 3.07728781, 3.55185431,
       3.30713012, 3.24264199, 3.28232277, 3.62791723, 3.24594696,
       3.21287824, 3.48571263, 3.22279949, 3.33854319, 3.38815155,
       3.33689176, 3.26082672, 3.50224382, 3.20956693, 3.30712801,
       3.3550786 , 3.34681512, 3.52208633, 3.10209094, 3.57831097,
       3.46256094, 3.29555321, 3.52209055, 3.35838992, 3.54358237,
       3.25090547, 3.35508283, 3.43279718, 2.98138027, 3.39476783,
       3.40799617, 3.14012028, 3.51712993, 3.22445092, 3.40634051,
       3.53531889, 3.26082672, 3.40137778, 3.64610196, 3.41791742,
       3.30878155, 3.33027548, 3.47744281, 3.35673426, 3.46421236,
       3.46751945, 3.22776011, 3.55350785, 3.46917299, 3.61303

### regressin

In [58]:
from sklearn.model_selection import train_test_split

In [ ]:
a=np.arange(0,101)